-- Initial schema of the modular monolith: one database, one schema, grouped by owning module.
-- Flyway applies it in every environment (dev, Testcontainers, docker-compose), and Hibernate only
-- validates the entities against it (spring.jpa.hibernate.ddl-auto=validate).
--
-- Foreign keys exist only inside a module. No constraint ever points from one module's table to
-- another module's table, even though nothing physical would prevent it here: a module boundary is
-- treated with the same discipline as if the modules were separate services with separate databases.

-- ---------------------------------------------------------------------------------------------
-- auth module
-- ---------------------------------------------------------------------------------------------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(50)  NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    email          VARCHAR(100) NOT NULL UNIQUE,
    password       VARCHAR(255) NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT FALSE,
    account_locked BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE role_user (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE activation_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    token        VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    validated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_activation_tokens_user_id ON activation_tokens (user_id);

CREATE TABLE blacklisted_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id),
    token          VARCHAR(1024) NOT NULL,
    jti            VARCHAR(255) NOT NULL UNIQUE,
    blacklisted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    validated_at   TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_blacklisted_tokens_user_id ON blacklisted_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token       VARCHAR(255) NOT NULL UNIQUE,
    type        VARCHAR(50)  NOT NULL,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- The two roles of the role-only authorization model (hasRole('ADMIN') / hasRole('USER')).
INSERT INTO roles (role_name) VALUES ('ADMIN'), ('USER');

-- ---------------------------------------------------------------------------------------------
-- catalog module
-- ---------------------------------------------------------------------------------------------
CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT         NOT NULL REFERENCES categories (id),
    product_name VARCHAR(150)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
);

CREATE INDEX idx_products_category_id ON products (category_id);

-- ---------------------------------------------------------------------------------------------
-- customer module
-- ---------------------------------------------------------------------------------------------
-- No user_id column on purpose: customer never points at auth's users table.
CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    telephone  VARCHAR(30)  NOT NULL,
    email      VARCHAR(100) NOT NULL UNIQUE,
    address    VARCHAR(255) NOT NULL
);

-- ---------------------------------------------------------------------------------------------
-- order module
-- ---------------------------------------------------------------------------------------------
-- customer_id and product_id are plain columns, not foreign keys: they reference rows owned by the
-- customer and catalog modules, which order only reaches through CustomerApi and CatalogApi.
-- total is a snapshot of quantity * unit price at creation time, never recalculated.
CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT         NOT NULL,
    product_id  BIGINT         NOT NULL,
    quantity    INTEGER        NOT NULL CHECK (quantity > 0),
    total       NUMERIC(14, 2) NOT NULL CHECK (total >= 0)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_product_id ON orders (product_id);

-- Event Publication Registry of Spring Modulith (spring-modulith-starter-jpa, schema v2 of 2.0.x).
-- A row is written in the publishing transaction for every (event, listener) pair, and its
-- completion_date is set once that listener has processed the event successfully. Rows left
-- incomplete are what gets retried: at-least-once delivery between modules without a broker.
CREATE TABLE event_publication (
    id                     UUID                     NOT NULL,
    listener_id            TEXT                     NOT NULL,
    event_type             TEXT                     NOT NULL,
    serialized_event       TEXT                     NOT NULL,
    publication_date       TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date        TIMESTAMP WITH TIME ZONE,
    status                 TEXT,
    completion_attempts    INT,
    last_resubmission_date TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

CREATE INDEX event_publication_serialized_event_hash_idx ON event_publication USING hash (serialized_event);
CREATE INDEX event_publication_by_completion_date_idx ON event_publication (completion_date);
